

info: 
    title:
    version:
    contact:
        name:
        url:
        email:
        x-security-contact:

    paths: the string of path name
        method:

    path_item: the object of the path
        methods:
            responses:
        details:
server:
    url:
    variables:


paths:
  /register:
    post:
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [username, age]
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 20
                  pattern: '^[a-zA-Z0-9_]+$' # Only alphanumeric and underscore
                age:
                  type: integer
                  minimum: 18
                  maximum: 120
      parameters:
        - name: promo_code
          in: query
          schema:
            type: string
            enum: [SUMMER20, WINTER20, WELCOME] # Restricted to specific values



openapi: 3.0.0
info:
  title: SEC-CHECK Demo API
  version: 1.0.0
  contact:
    name: Security Team
    email: security@example.com
    url: https://example.com/support
    x-security-contact: security@example.com

servers:
  - url: https://api.example.com
    description: Production server

paths:
  /v1/search:
    get:
      summary: Search for items
      security: []  # Explicitly public
      parameters:
        - name: api_key
          in: query
          description: Search authorization
          schema:
            type: string
        - name: query
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful search
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests

  /v1/user/profile:
    post:
      summary: Update user profile
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[U]-[0-9]{6}$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - age
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 15
                  pattern: '^[a-z]+$'
                age:
                  type: integer
                  minimum: 18
      responses:
        '200':
          description: Profile updated
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests

  /v1/old-login:
    post:
      summary: Legacy login
      deprecated: true
      responses:
        '200':
          description: Login success

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT



openapi: 3.0.0
info:
  title: Secure Sample API
  version: 1.0.0
  description: An example of a secure OpenAPI spec
  contact:
    name: API Security Team
    email: security@example.com
  x-security-contact: security@example.com

servers:
  - url: https://api.example.com
    description: Production server

paths:
  /users:
    get:
      summary: List all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          headers:
            X-RateLimit-Limit:
              description: Max requests
              schema:
                type: integer
            X-RateLimit-Remaining:
              description: Remaining requests
              schema:
                type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests
    post:
      summary: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                  pattern: '^[a-zA-Z0-9_]+$'
                password:
                  type: string
                  minLength: 8
      responses:
        '201':
          description: Created
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
            X-RateLimit-Remaining:
              schema:
                type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests

  /login:
    post:
      summary: User login
      security: []  # public endpoint allowed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized
        '429':
          description: Too Many Requests

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

